version: '3.8'

services:
  redis:
    container_name: redis
    image: bitnami/redis:6.2.6
  database:
    container_name: database
    image: bitnami/postgresql:11.15.0
    restart: always
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

    ports:
      - "5432:5432"
    volumes:
        - ./database/:/docker-entrypoint-initdb.d
        - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
        


    
