version: '3.8'

services:

  client:
    container_name: client
    build: ./grpcClient
    ports: 
     - "3000:3000"
    networks:
      - redis
    depends_on:
      - database
      - redis-server
  
  server:
    container_name: server
    build: ./grpcServer
    ports:
      - "3001:3001"
    networks:
      - redis
    depends_on:
      - database

  redis-server:  
    container_name: redis
    image: bitnami/redis:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
    networks:
      - redis


  database:
    container_name: database
    image: bitnami/postgresql:11.15.0
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata 
    networks:
      - redis

networks:
  redis:
    driver: bridge        


    
